### ISSUE TITLE
unsearchable() not removing model from index

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-migrations#16] opened 2020-12-24 00:14 UTC
Software | Version
-- | --
PHP | 7.4.7
Elasticsearch | 7.3.2
Laravel | 8.15.0
Laravel Scout | 8.5.0
Elastic Scout Driver | 1.2.1

**Describe the bug**
unsearchable() does not remove model from index

**To Reproduce**
In my event when an event is published I change the status to 'p', In my event model I have
```
    public function shouldBeSearchable()
    {
        return $this->status === 'p';
    }
```
This works great but now I am running into an issue. After an event has been published if I go back to the event and decide I want to embargo it (publish it at a certain time in the future) I update the event status to 'e' and add an embargo date. I just discovered however that after updating the event it still remains in my index and searchable.
I went and looked at the laravel scout documentation and they have unsearchable(). So now I tried 
```
$event->update([
                'show_times' => $request->showtimes,
                'embargo_date' => $request->embargo_date,
                'closingDate' => $lastDate,
                'showtype' => $type,
                'timezone_id' => $request->timezone ? $request->timezone['id'] : null,
                'status' => 'e'
            ]);
            return $event->unsearchable();
```
However this still doesn't remove the event from the index.

**Current behavior**
Event is remaining in index even with $event->unsearchable();

**Expected behavior**
I expected the event to drop from the index when the status changed away from 'p'

**Comment by babenkoivan** [comment] 2021-01-17 14:01
Hey @chrisgrim, I think this bug is created in a wrong repository, isn't it? 

Anyways, I believe this is a Scout bug, because elastic-scout-driver doesn't change `shouldBeSearchable` logic, it comes with Laravel Scout. I'll try to reproduce the issue and see what can be done here. 

Please, reopen the bug in the related repository, I'm closing it here as unrelated.

**Closed by babenkoivan** 2021-01-17 14:01 UTC
Labels: bug

**Comment by chrisgrim** [comment] 2021-01-17 17:25
Good call! I just opened the same bug in the scout git. 
Thanks!
